<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Archivo extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Archivo_model');
    } 

    /*
     * Listing of archivo
     */
    function index()
    {
        $data['archivo'] = $this->Archivo_model->get_all_archivo();
        
        $data['_view'] = 'archivo/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new archivo
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'empleoidempleo' => $this->input->post('empleoidempleo'),
				'ruta' => $this->input->post('ruta'),
				'fechacreacion' => $this->input->post('fechacreacion'),
            );
            
            $archivo_id = $this->Archivo_model->add_archivo($params);
            redirect('archivo/index');
        }
        else
        {
			$this->load->model('Empleo_model');
			$data['all_empleo'] = $this->Empleo_model->get_all_empleo();
            
            $data['_view'] = 'archivo/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a archivo
     */
    function edit($idarchivo)
    {   
        // check if the archivo exists before trying to edit it
        $data['archivo'] = $this->Archivo_model->get_archivo($idarchivo);
        
        if(isset($data['archivo']['idarchivo']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'empleoidempleo' => $this->input->post('empleoidempleo'),
					'ruta' => $this->input->post('ruta'),
					'fechacreacion' => $this->input->post('fechacreacion'),
                );

                $this->Archivo_model->update_archivo($idarchivo,$params);            
                redirect('archivo/index');
            }
            else
            {
				$this->load->model('Empleo_model');
				$data['all_empleo'] = $this->Empleo_model->get_all_empleo();

                $data['_view'] = 'archivo/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The archivo you are trying to edit does not exist.');
    } 

    /*
     * Deleting archivo
     */
    function remove($idarchivo)
    {
        $archivo = $this->Archivo_model->get_archivo($idarchivo);

        // check if the archivo exists before trying to delete it
        if(isset($archivo['idarchivo']))
        {
            $this->Archivo_model->delete_archivo($idarchivo);
            redirect('archivo/index');
        }
        else
            show_error('The archivo you are trying to delete does not exist.');
    }
    
}
