<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Area extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Area_model');
    } 

    /*
     * Listing of area
     */
    function index()
    {
        $data['area'] = $this->Area_model->get_all_area();
        
        $data['_view'] = 'area/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new area
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'nombre' => $this->input->post('nombre'),
				'descripcion' => $this->input->post('descripcion'),
            );
            
            $area_id = $this->Area_model->add_area($params);
            redirect('area/index');
        }
        else
        {            
            $data['_view'] = 'area/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a area
     */
    function edit($idarea)
    {   
        // check if the area exists before trying to edit it
        $data['area'] = $this->Area_model->get_area($idarea);
        
        if(isset($data['area']['idarea']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'nombre' => $this->input->post('nombre'),
					'descripcion' => $this->input->post('descripcion'),
                );

                $this->Area_model->update_area($idarea,$params);            
                redirect('area/index');
            }
            else
            {
                $data['_view'] = 'area/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The area you are trying to edit does not exist.');
    } 

    /*
     * Deleting area
     */
    function remove($idarea)
    {
        $area = $this->Area_model->get_area($idarea);

        // check if the area exists before trying to delete it
        if(isset($area['idarea']))
        {
            $this->Area_model->delete_area($idarea);
            redirect('area/index');
        }
        else
            show_error('The area you are trying to delete does not exist.');
    }
    
}
