<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Detalle extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Detalle_model');
    } 

    /*
     * Listing of detalle
     */
    function index()
    {
        $data['detalle'] = $this->Detalle_model->get_all_detalle();
        
        $data['_view'] = 'detalle/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new detalle
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'perfilidperfil' => $this->input->post('perfilidperfil'),
				'requisitoidRequi' => $this->input->post('requisitoidRequi'),
            );
            
            $detalle_id = $this->Detalle_model->add_detalle($params);
            redirect('detalle/index');
        }
        else
        {
			$this->load->model('Perfil_model');
			$data['all_perfil'] = $this->Perfil_model->get_all_perfil();

			$this->load->model('Requisito_model');
			$data['all_requisito'] = $this->Requisito_model->get_all_requisito();
            
            $data['_view'] = 'detalle/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a detalle
     */
    function edit($iddetalle)
    {   
        // check if the detalle exists before trying to edit it
        $data['detalle'] = $this->Detalle_model->get_detalle($iddetalle);
        
        if(isset($data['detalle']['iddetalle']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'perfilidperfil' => $this->input->post('perfilidperfil'),
					'requisitoidRequi' => $this->input->post('requisitoidRequi'),
                );

                $this->Detalle_model->update_detalle($iddetalle,$params);            
                redirect('detalle/index');
            }
            else
            {
				$this->load->model('Perfil_model');
				$data['all_perfil'] = $this->Perfil_model->get_all_perfil();

				$this->load->model('Requisito_model');
				$data['all_requisito'] = $this->Requisito_model->get_all_requisito();

                $data['_view'] = 'detalle/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The detalle you are trying to edit does not exist.');
    } 

    /*
     * Deleting detalle
     */
    function remove($iddetalle)
    {
        $detalle = $this->Detalle_model->get_detalle($iddetalle);

        // check if the detalle exists before trying to delete it
        if(isset($detalle['iddetalle']))
        {
            $this->Detalle_model->delete_detalle($iddetalle);
            redirect('detalle/index');
        }
        else
            show_error('The detalle you are trying to delete does not exist.');
    }
    
}
