<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Empleo extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Empleo_model');
    } 

    /*
     * Listing of empleo
     */
    function index()
    {
        $data['empleo'] = $this->Empleo_model->get_all_empleo();
        
        $data['_view'] = 'empleo/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new empleo
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'UsuarioidUsuario' => $this->input->post('UsuarioidUsuario'),
				'AreaidArea' => $this->input->post('AreaidArea'),
				'PerfilidPerfil' => $this->input->post('PerfilidPerfil'),
				'titulo' => $this->input->post('titulo'),
				'fecha' => $this->input->post('fecha'),
				'descripcion' => $this->input->post('descripcion'),
            );
            
            $empleo_id = $this->Empleo_model->add_empleo($params);
            redirect('empleo/index');
        }
        else
        {
			$this->load->model('Usuario_model');
			$data['all_usuario'] = $this->Usuario_model->get_all_usuario();

			$this->load->model('Area_model');
			$data['all_area'] = $this->Area_model->get_all_area();

			$this->load->model('Perfil_model');
			$data['all_perfil'] = $this->Perfil_model->get_all_perfil();
            
            $data['_view'] = 'empleo/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a empleo
     */
    function edit($idempleo)
    {   
        // check if the empleo exists before trying to edit it
        $data['empleo'] = $this->Empleo_model->get_empleo($idempleo);
        
        if(isset($data['empleo']['idempleo']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'UsuarioidUsuario' => $this->input->post('UsuarioidUsuario'),
					'AreaidArea' => $this->input->post('AreaidArea'),
					'PerfilidPerfil' => $this->input->post('PerfilidPerfil'),
					'titulo' => $this->input->post('titulo'),
					'fecha' => $this->input->post('fecha'),
					'descripcion' => $this->input->post('descripcion'),
                );

                $this->Empleo_model->update_empleo($idempleo,$params);            
                redirect('empleo/index');
            }
            else
            {
				$this->load->model('Usuario_model');
				$data['all_usuario'] = $this->Usuario_model->get_all_usuario();

				$this->load->model('Area_model');
				$data['all_area'] = $this->Area_model->get_all_area();

				$this->load->model('Perfil_model');
				$data['all_perfil'] = $this->Perfil_model->get_all_perfil();

                $data['_view'] = 'empleo/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The empleo you are trying to edit does not exist.');
    } 

    /*
     * Deleting empleo
     */
    function remove($idempleo)
    {
        $empleo = $this->Empleo_model->get_empleo($idempleo);

        // check if the empleo exists before trying to delete it
        if(isset($empleo['idempleo']))
        {
            $this->Empleo_model->delete_empleo($idempleo);
            redirect('empleo/index');
        }
        else
            show_error('The empleo you are trying to delete does not exist.');
    }
    
}
