<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Perfil extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Perfil_model');
    } 

    /*
     * Listing of perfil
     */
    function index()
    {
        $data['perfil'] = $this->Perfil_model->get_all_perfil();
        
        $data['_view'] = 'perfil/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new perfil
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'nombre' => $this->input->post('nombre'),
				'descripcion' => $this->input->post('descripcion'),
            );
            
            $perfil_id = $this->Perfil_model->add_perfil($params);
            redirect('perfil/index');
        }
        else
        {            
            $data['_view'] = 'perfil/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a perfil
     */
    function edit($idperfil)
    {   
        // check if the perfil exists before trying to edit it
        $data['perfil'] = $this->Perfil_model->get_perfil($idperfil);
        
        if(isset($data['perfil']['idperfil']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'nombre' => $this->input->post('nombre'),
					'descripcion' => $this->input->post('descripcion'),
                );

                $this->Perfil_model->update_perfil($idperfil,$params);            
                redirect('perfil/index');
            }
            else
            {
                $data['_view'] = 'perfil/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The perfil you are trying to edit does not exist.');
    } 

    /*
     * Deleting perfil
     */
    function remove($idperfil)
    {
        $perfil = $this->Perfil_model->get_perfil($idperfil);

        // check if the perfil exists before trying to delete it
        if(isset($perfil['idperfil']))
        {
            $this->Perfil_model->delete_perfil($idperfil);
            redirect('perfil/index');
        }
        else
            show_error('The perfil you are trying to delete does not exist.');
    }
    
}
