<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Requisito extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Requisito_model');
    } 

    /*
     * Listing of requisito
     */
    function index()
    {
        $data['requisito'] = $this->Requisito_model->get_all_requisito();
        
        $data['_view'] = 'requisito/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new requisito
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'requisito' => $this->input->post('requisito'),
            );
            
            $requisito_id = $this->Requisito_model->add_requisito($params);
            redirect('requisito/index');
        }
        else
        {            
            $data['_view'] = 'requisito/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a requisito
     */
    function edit($idrequi)
    {   
        // check if the requisito exists before trying to edit it
        $data['requisito'] = $this->Requisito_model->get_requisito($idrequi);
        
        if(isset($data['requisito']['idrequi']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'requisito' => $this->input->post('requisito'),
                );

                $this->Requisito_model->update_requisito($idrequi,$params);            
                redirect('requisito/index');
            }
            else
            {
                $data['_view'] = 'requisito/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The requisito you are trying to edit does not exist.');
    } 

    /*
     * Deleting requisito
     */
    function remove($idrequi)
    {
        $requisito = $this->Requisito_model->get_requisito($idrequi);

        // check if the requisito exists before trying to delete it
        if(isset($requisito['idrequi']))
        {
            $this->Requisito_model->delete_requisito($idrequi);
            redirect('requisito/index');
        }
        else
            show_error('The requisito you are trying to delete does not exist.');
    }
    
}
