<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Archivo_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get archivo by idarchivo
     */
    function get_archivo($idarchivo)
    {
        return $this->db->get_where('archivo',array('idarchivo'=>$idarchivo))->row_array();
    }
        
    /*
     * Get all archivo
     */
    function get_all_archivo()
    {
        $this->db->order_by('idarchivo', 'desc');
        return $this->db->get('archivo')->result_array();
    }
        
    /*
     * function to add new archivo
     */
    function add_archivo($params)
    {
        $this->db->insert('archivo',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update archivo
     */
    function update_archivo($idarchivo,$params)
    {
        $this->db->where('idarchivo',$idarchivo);
        return $this->db->update('archivo',$params);
    }
    
    /*
     * function to delete archivo
     */
    function delete_archivo($idarchivo)
    {
        return $this->db->delete('archivo',array('idarchivo'=>$idarchivo));
    }
}
