<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Empleo_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get empleo by idempleo
     */
    function get_empleo($idempleo)
    {
        return $this->db->get_where('empleo',array('idempleo'=>$idempleo))->row_array();
    }
        
    /*
     * Get all empleo
     */
    function get_all_empleo()
    {
        $this->db->order_by('idempleo', 'desc');
        return $this->db->get('empleo')->result_array();
    }
        
    /*
     * function to add new empleo
     */
    function add_empleo($params)
    {
        $this->db->insert('empleo',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update empleo
     */
    function update_empleo($idempleo,$params)
    {
        $this->db->where('idempleo',$idempleo);
        return $this->db->update('empleo',$params);
    }
    
    /*
     * function to delete empleo
     */
    function delete_empleo($idempleo)
    {
        return $this->db->delete('empleo',array('idempleo'=>$idempleo));
    }
}
