<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Perfil_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get perfil by idperfil
     */
    function get_perfil($idperfil)
    {
        return $this->db->get_where('perfil',array('idperfil'=>$idperfil))->row_array();
    }
        
    /*
     * Get all perfil
     */
    function get_all_perfil()
    {
        $this->db->order_by('idperfil', 'desc');
        return $this->db->get('perfil')->result_array();
    }
        
    /*
     * function to add new perfil
     */
    function add_perfil($params)
    {
        $this->db->insert('perfil',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update perfil
     */
    function update_perfil($idperfil,$params)
    {
        $this->db->where('idperfil',$idperfil);
        return $this->db->update('perfil',$params);
    }
    
    /*
     * function to delete perfil
     */
    function delete_perfil($idperfil)
    {
        return $this->db->delete('perfil',array('idperfil'=>$idperfil));
    }
}
