<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Requisito_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get requisito by idrequi
     */
    function get_requisito($idrequi)
    {
        return $this->db->get_where('requisito',array('idrequi'=>$idrequi))->row_array();
    }
        
    /*
     * Get all requisito
     */
    function get_all_requisito()
    {
        $this->db->order_by('idrequi', 'desc');
        return $this->db->get('requisito')->result_array();
    }
        
    /*
     * function to add new requisito
     */
    function add_requisito($params)
    {
        $this->db->insert('requisito',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update requisito
     */
    function update_requisito($idrequi,$params)
    {
        $this->db->where('idrequi',$idrequi);
        return $this->db->update('requisito',$params);
    }
    
    /*
     * function to delete requisito
     */
    function delete_requisito($idrequi)
    {
        return $this->db->delete('requisito',array('idrequi'=>$idrequi));
    }
}
